import { createRecord, exportRows, nextRecordId, partitionPhotoFiles, photoNumber, toCsv } from "./scanner-core.mjs";
import { detectStampGroups } from "./stamp-detector.mjs";
import { identifyStampGroups, canonicalIdentificationFields, getStoredApiKey, setStoredApiKey } from "./ai-identify.mjs";
const USAGE_LABELS={used:"Used",unused:"Unused",uncertain:"Uncertain"};
const CONFIDENCE_LABELS={high:"High",medium:"Medium",low:"Low"};
function aiFieldsFor(ai){return Object.fromEntries(Object.entries({country:ai.country,period:ai.period,denomination:ai.denomination,currency:ai.currency,colour:ai.colour,subject:ai.subject}).filter(([,v])=>v))}

const MAX_FILES=100, STORAGE_KEY="stampScannerBetaV1", PHOTO_SEQUENCE_KEY="stampScannerBetaPhotoSequence";
const dbPromise=openDatabase(); let photos=[], records=[], nextPhotoSequence=readPhotoSequence();
const $=s=>document.querySelector(s);
const fields=[["country","Country / Possible Country"],["period","Approximate Period"],["denomination","Denomination"],["currency","Currency"],["colour","Main Colour"],["subject","Subject / Design"],["usage","Used / Unused",["Uncertain","Used","Unused"]],["quantity","Quantity","number"],["confidence","Confidence",["Needs review","Low","Medium","High","User confirmed"]],["furtherResearch","Further Research",["No","Yes"]],["notes","Collector Notes","textarea"],["status","Information Status",["Local detection — manual review","AI not connected — manual review","AI suggestion","User confirmed"]]];
function readPhotoSequence(){const v=parseInt(sessionStorage.getItem(PHOTO_SEQUENCE_KEY)||"1",10);return Number.isFinite(v)&&v>0?v:1} function writePhotoSequence(){sessionStorage.setItem(PHOTO_SEQUENCE_KEY,String(nextPhotoSequence))} function photoSequenceFromLabel(v=""){return parseInt(String(v).replace(/\D/g,""),10)||0} function syncPhotoSequenceFromRestoredPhotos(){const h=Math.max(0,...photos.map(p=>photoSequenceFromLabel(p.number)));nextPhotoSequence=Math.max(nextPhotoSequence,h+1);writePhotoSequence()} function takeNextPhotoNumber(){const n=photoNumber(nextPhotoSequence-1);nextPhotoSequence++;writePhotoSequence();return n}
function openDatabase(){return new Promise((res,rej)=>{const r=indexedDB.open("stampScannerBeta",1);r.onupgradeneeded=()=>r.result.createObjectStore("photos",{keyPath:"id"});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})} async function storePhoto(p){const db=await dbPromise;return new Promise((res,rej)=>{const tx=db.transaction("photos","readwrite");tx.objectStore("photos").put(p);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})} async function removeStoredPhotos(){const db=await dbPromise;return new Promise((res,rej)=>{const tx=db.transaction("photos","readwrite");tx.objectStore("photos").clear();tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})} async function loadStoredPhotos(ids){const db=await dbPromise;return Promise.all(ids.map(id=>new Promise(res=>{const r=db.transaction("photos").objectStore("photos").get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>res(null)})))}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({photoIds:photos.map(p=>p.id),records}))} async function restoreState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(!s)return;photos=(await loadStoredPhotos(s.photoIds||[])).filter(Boolean);records=(s.records||[]).filter(r=>photos.some(p=>p.id===r.photoId));syncPhotoSequenceFromRestoredPhotos();render()}catch{showMessage("The previous session could not be restored. You can start a new inventory.")}} function showMessage(m=""){$("#messages").textContent=m} function newId(){return crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
async function addFiles(list){const {accepted,unsupported,overLimit}=partitionPhotoFiles(list,photos.length,MAX_FILES);if(unsupported.length)showMessage(`${unsupported.length} unsupported file(s) were not added. Use JPG, PNG or WebP.`);else if(overLimit)showMessage(`This Beta supports up to ${MAX_FILES} photos per inventory.`);else showMessage("");for(const file of accepted){const p={id:newId(),number:takeNextPhotoNumber(),name:file.name,type:file.type,size:file.size,blob:file};photos.push(p);try{await storePhoto(p)}catch{showMessage("A photo could not be saved for recovery, but remains available in this session.")}}if(accepted.length)gtag?.("event","photos_selected",{photo_count:accepted.length});saveState();render()}
function imageUrl(p){return URL.createObjectURL(p.blob)} function revokeImageUrl(i,u){i.onload=i.onerror=()=>URL.revokeObjectURL(u)} function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderPhotos(){$("#photo-grid").innerHTML=photos.map(p=>`<article class="photo-card"><img data-photo="${p.id}" alt="Preview of ${escapeHtml(p.name)}"><div><strong>${p.number}</strong><small title="${escapeHtml(p.name)}">${escapeHtml(p.name)}</small></div></article>`).join("");document.querySelectorAll("[data-photo]").forEach(i=>{const p=photos.find(x=>x.id===i.dataset.photo),u=imageUrl(p);i.src=u;revokeImageUrl(i,u)})}
function createField(r,[key,label,type]){const w=document.createElement("div");w.className=`field ${key==="notes"||key==="status"?"wide-field":""}`;const l=document.createElement("label");l.textContent=label;let c;if(Array.isArray(type)){c=document.createElement("select");for(const o of type)c.add(new Option(o,o,false,o===r[key]))}else if(type==="textarea"){c=document.createElement("textarea");c.value=r[key]||""}else{c=document.createElement("input");c.type=type||"text";c.value=r[key]??"";if(type==="number"){c.min="1";c.step="1"}}c.dataset.field=key;c.setAttribute("aria-label",label);w.append(l,c);return w}
function renderRecords(){const c=$("#records");c.innerHTML="";for(const r of records){const p=photos.find(x=>x.id===r.photoId);if(!p)continue;const card=$("#record-template").content.firstElementChild.cloneNode(true);card.dataset.id=r.id;const img=new Image();img.alt=`${p.number}: ${p.name}`;const u=imageUrl(p);img.src=u;revokeImageUrl(img,u);card.querySelector(".record-photo").append(img);card.querySelector(".record-id").textContent=r.id;const ss=card.querySelector(".record-photo-select");for(const op of photos)ss.add(new Option(`${op.number} · ${op.name}`,op.id,false,op.id===r.photoId));const fc=card.querySelector(".fields");for(const f of fields)fc.append(createField(r,f));c.append(card)}$("#empty-state").hidden=Boolean(records.length)}
function render(){renderPhotos();renderRecords();$("#photo-count").textContent=`${photos.length} photo${photos.length===1?"":"s"}`;$("#row-count").textContent=`${records.length} record${records.length===1?"":"s"}`;$("#create-inventory").disabled=!photos.length;$("#add-row").disabled=!photos.length;$("#export-xlsx").disabled=!records.length;$("#export-csv").disabled=!records.length}
function nextSequence(id){const used=records.filter(r=>r.photoId===id).map(r=>Number(r.id.match(/-(\d+)$/)?.[1]||0));return Math.max(0,...used)+1} function addRecord(p=photos[0],extra={}){if(!p)return;const r={...createRecord(p,nextSequence(p.id)),...extra};records.push(r);return r}
async function createInventory(){showMessage("Scanning photos locally…");let added=0, detected=0, duplicates=0, aiIdentified=0, aiFailed=false;for(const p of photos){if(records.some(r=>r.photoId===p.id))continue;try{const result=await detectStampGroups(p.blob);detected+=result.totalDetected;let identifications=null;if(result.groups.length){try{identifications=await identifyStampGroups(p.blob,result.groups,{lang:"en"})}catch{aiFailed=true}}result.groups.forEach((g,i)=>{const localExtra={quantity:g.quantity,status:result.detected?"Local detection — manual review":"AI not connected — manual review",confidence:result.detected?"Low":"Needs review",notes:result.detected?"Stamp region detected locally. Check the crop/source photo and details.":"Could not reliably separate stamp regions; check this photo."};const ai=canonicalIdentificationFields(identifications?.[i]);if(ai&&ai.emptySlot){addRecord(p,{...localExtra,status:"AI suggestion",confidence:"High",notes:`${localExtra.notes} AI review: this looks like an empty pre-printed album slot, not a mounted stamp — verify and delete this row if so.${ai.aiNotes?` ${ai.aiNotes}`:""}`})}else if(ai){aiIdentified++;addRecord(p,{...localExtra,...aiFieldsFor(ai),usage:USAGE_LABELS[ai.usageKey],confidence:CONFIDENCE_LABELS[ai.confidenceKey],status:"AI suggestion",notes:[localExtra.notes,ai.aiNotes].filter(Boolean).join(" ")})}else{addRecord(p,localExtra)}added++;duplicates+=Math.max(0,g.quantity-1)})}catch{addRecord(p,{notes:"Automatic separation could not run for this photo; check it manually."});added++}}saveState();render();showMessage(`Inventory ready: ${added} record${added===1?"":"s"}${duplicates?`, including ${duplicates} similar stamp${duplicates===1?"":"s"} counted in Quantity`:""}.${aiIdentified?` AI identified ${aiIdentified} row${aiIdentified===1?"":"s"}.`:""}${aiFailed?" AI identification was unavailable for some photos; rows were added from local detection only.":""} Check the detected records before export.`);gtag?.("event","inventory_created",{record_count:records.length,detected_stamp_count:detected,ai_identified_count:aiIdentified})}
function duplicateRecord(id){const s=records.find(r=>r.id===id);if(!s)return;const p=photos.find(x=>x.id===s.photoId);records.push({...s,id:createRecord(p,nextSequence(p.id)).id,quantity:1});saveState();render()} function download(n,t,d){const u=URL.createObjectURL(new Blob([d],{type:t})),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)} function exportExcel(){if(!XLSX)return showMessage("Excel could not load. Saving as CSV remains available.");try{const rows=exportRows(records),sheet=XLSX.utils.json_to_sheet(rows);sheet["!freeze"]={xSplit:0,ySplit:1};sheet["!cols"]=Object.keys(rows[0]).map(k=>({wch:Math.min(42,Math.max(12,k.length+2))}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,sheet,"Inventory");XLSX.writeFile(wb,"AI-Stamp-Inventory-Beta-v1.xlsx");gtag?.("event","inventory_export",{format:"xlsx",record_count:records.length})}catch{showMessage("Saving as Excel failed. Your inventory is unchanged; save as CSV or try again.")}}
$("#photo-input").addEventListener("change",e=>{addFiles(e.target.files);e.target.value=""});$("#camera-input").addEventListener("change",e=>{addFiles(e.target.files);e.target.value=""});$("#create-inventory").onclick=createInventory;$("#add-row").onclick=()=>{addRecord();saveState();render()};$("#export-xlsx").onclick=exportExcel;$("#export-csv").onclick=()=>{download("AI-Stamp-Inventory-Beta-v1.csv","text/csv;charset=utf-8",toCsv(records));gtag?.("event","inventory_export",{format:"csv",record_count:records.length})};$("#clear-all").onclick=async()=>{if(!photos.length||confirm("Clear all photos and inventory records from this browser? Photo numbering will continue in this browser session.")){photos=[];records=[];localStorage.removeItem(STORAGE_KEY);let ok=true;try{await removeStoredPhotos()}catch{ok=false}render();const n=photoNumber(nextPhotoSequence-1);showMessage(ok?`Inventory cleared. The next photo will be ${n}.`:`Inventory cleared from this session. The next photo will be ${n}, but browser recovery storage could not be cleared.`)}};
$("#records").addEventListener("input",e=>{const card=e.target.closest(".record-card"),r=records.find(x=>x.id===card?.dataset.id),f=e.target.dataset.field;if(!r||!f)return;if(f==="photoId"){const p=photos.find(x=>x.id===e.target.value);if(!p||p.id===r.photoId)return;r.id=nextRecordId(p,records);r.photoId=p.id;r.photoNumber=p.number;r.filename=p.name;r.imageReference=`${p.number} — ${p.name}`;saveState();render();return}r[f]=e.target.value;saveState()});$("#records").addEventListener("click",e=>{const b=e.target.closest("button[data-action]");if(!b)return;const id=b.closest(".record-card").dataset.id;if(b.dataset.action==="duplicate")duplicateRecord(id);else{records=records.filter(r=>r.id!==id);saveState();render()}});const apiKeyInput=$("#gemini-api-key");if(apiKeyInput){apiKeyInput.value=getStoredApiKey();apiKeyInput.addEventListener("change",()=>setStoredApiKey(apiKeyInput.value));apiKeyInput.addEventListener("blur",()=>setStoredApiKey(apiKeyInput.value))}
$("#clear-api-key")?.addEventListener("click",()=>{setStoredApiKey("");if(apiKeyInput)apiKeyInput.value=""});
restoreState().then(render);
