import {detectStampGroups} from '../../beta/heuristic-stamp-detector.mjs';
const $=s=>document.querySelector(s),stage=$('#stage'),img=$('#image'),status=$('#status');let file=null,boxes=[],start=null;
function setStatus(t){status.textContent=t}function buttons(on){for(const id of['auto','clear','labels'])$('#'+id).disabled=!on}
function render(){stage.querySelectorAll('.box').forEach(e=>e.remove());const r=img.getBoundingClientRect(),sr=stage.getBoundingClientRect();for(const [i,b] of boxes.entries()){const e=document.createElement('div');e.className='box';e.style.left=`${b.x*100}%`;e.style.top=`${b.y*100}%`;e.style.width=`${b.width*100}%`;e.style.height=`${b.height*100}%`;e.title=`Stamp ${i+1} — click to remove`;e.onclick=ev=>{ev.stopPropagation();boxes.splice(i,1);render();setStatus(`${boxes.length} boxes. Click-and-drag to add missing stamps.`)};stage.append(e)}setStatus(`${boxes.length} stamp boxes. Review every visible stamp before export.`)}
async function load(f){file=f;boxes=[];const u=URL.createObjectURL(f);img.onload=()=>{URL.revokeObjectURL(u);buttons(true);render()};img.src=u;setStatus('Photo loaded. Running auto-detection is optional.')}
$('#file').onchange=e=>{if(e.target.files[0])load(e.target.files[0])};$('#clear').onclick=()=>{boxes=[];render()};
$('#auto').onclick=async()=>{if(!file)return;setStatus('Creating annotation suggestions…');try{const r=await detectStampGroups(file);boxes=r.groups.flatMap(g=>g.matches||[g]).map(b=>({x:b.normalized.x,y:b.normalized.y,width:b.normalized.width,height:b.normalized.height}));render();setStatus(`${boxes.length} suggestions from ${r.mode}. Correct false or missing boxes before export.`)}catch(e){console.error(e);setStatus('Auto-detection failed. You can still draw boxes manually.')}};
function point(ev){const r=img.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height))}}
stage.addEventListener('pointerdown',e=>{if(!file||e.target!==img)return;start=point(e);stage.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointerup',e=>{if(!start||e.target!==img){start=null;return}const p=point(e),x=Math.min(start.x,p.x),y=Math.min(start.y,p.y),w=Math.abs(start.x-p.x),h=Math.abs(start.y-p.y);start=null;if(w>.008&&h>.008){boxes.push({x,y,width:w,height:h});render()}});
$('#labels').onclick=()=>{if(!file||!boxes.length)return;const text=boxes.map(b=>`0 ${(b.x+b.width/2).toFixed(6)} ${(b.y+b.height/2).toFixed(6)} ${b.width.toFixed(6)} ${b.height.toFixed(6)}`).join('\n')+'\n',blob=new Blob([text],{type:'text/plain'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=file.name.replace(/\.[^.]+$/,'.txt');a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setStatus(`Exported ${boxes.length} YOLO annotations for ${file.name}.`)};
